
$background = rgba(000000ff)

$error = rgba(f8afa6ff)

$error_container = rgba(9d1b19ff)

$inverse_on_surface = rgba(1d1b18ff)

$inverse_primary = rgba(553d13ff)

$inverse_surface = rgba(e6ded6ff)

$on_background = rgba(e6ded6ff)

$on_error = rgba(160000ff)

$on_error_container = rgba(ffffffff)

$on_primary = rgba(0f0900ff)

$on_primary_container = rgba(ffffffff)

$on_primary_fixed = rgba(000000ff)

$on_primary_fixed_variant = rgba(3c2805ff)

$on_secondary = rgba(120d05ff)

$on_secondary_container = rgba(ffffffff)

$on_secondary_fixed = rgba(000000ff)

$on_secondary_fixed_variant = rgba(3b2f1eff)

$on_surface = rgba(ebe2dbff)

$on_surface_variant = rgba(cbbeafff)

$on_tertiary = rgba(030400ff)

$on_tertiary_container = rgba(ffffffff)

$on_tertiary_fixed = rgba(000000ff)

$on_tertiary_fixed_variant = rgba(272e0eff)

$outline = rgba(95897cff)

$outline_variant = rgba(5b5348ff)

$primary = rgba(e2b778ff)

$primary_container = rgba(684b1eff)

$primary_fixed = rgba(fad9acff)

$primary_fixed_dim = rgba(e2b778ff)

$scrim = rgba(000000ff)

$secondary = rgba(d3bc9dff)

$secondary_container = rgba(60503aff)

$secondary_fixed = rgba(f4dbbbff)

$secondary_fixed_dim = rgba(d3bc9dff)

$shadow = rgba(000000ff)

$source_color = rgba(72511aff)

$surface = rgba(000000ff)

$surface_bright = rgba(2c2925ff)

$surface_container = rgba(0d0b09ff)

$surface_container_high = rgba(191715ff)

$surface_container_highest = rgba(26231fff)

$surface_container_low = rgba(050404ff)

$surface_container_lowest = rgba(000000ff)

$surface_dim = rgba(000000ff)

$surface_tint = rgba(e2b778ff)

$surface_variant = rgba(393229ff)

$tertiary = rgba(b7c486ff)

$tertiary_container = rgba(4a5328ff)

$tertiary_fixed = rgba(d6e3a2ff)

$tertiary_fixed_dim = rgba(b7c486ff)
